---
collections:
- name: community.mysql
  source: https://github.com/ansible-collections/community.mysql
  type: git
  version: 3.11.0
- name: community.general
  source: https://github.com/ansible-collections/community.general
  type: git
  version: 10.0.1
- name: monolithprojects.github_actions_runner
  version: 1.21.1
  source: https://github.com/MonolithProjects/ansible-github_actions_runner