name: Deploy Docker

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        echo "${{ secrets.SUDO_PASSWORD }}" > $HOME/.askpass
        chmod +x $HOME/.askpass
        sudo -A apt-get update
        sudo chmod 666 ~/var/run/docker.sock
        cd ./hello-world-app/app
        docker build . --file Dockerfile --tag app
      env:
          SUDO_ASKPASS: $HOME/.askpass  

  deploy:
    runs-on: self-hosted
    needs: [ build ]

    steps:
    - uses: actions/checkout@v4
    - name: Deploy
      run: |
        echo "${{ secrets.SUDO_PASSWORD }}" > $HOME/.askpass
        chmod +x $HOME/.askpass
        sudo -A apt-get update
        sudo chmod 666 ~/var/run/docker.sock
        cd ./hello-world/app/app
        docker run -p 8000:8000 -d app
        docker image prune -f
        docker container prune -f
      env:
          SUDO_ASKPASS: $HOME/.askpass